<?php

namespace Junior\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{
    public function findEtudesbyStatut($statut)
    {
       $qb = $this->createQueryBuilder('e')
               ->leftJoin('e.participants', 'part')
               ->addSelect('part')
               ->leftJoin('part.etude', 'etude')
               ->addSelect('etude');
       
       $qb->where('etude.statutEtude = :statut')
                ->setParameter('statutEtude', $statut);
               
        return $qb->getQuery()
                        ->getResult();
    }
    
}
