<?php

namespace Junior\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudeRepository extends EntityRepository
{
    public function findEtudesbyStudentAndStatut($idStudent, $statut) {
        $qb = $this->createQueryBuilder('e')
                ->leftJoin('e.participants', 'part')
                ->addSelect('part')
                ->leftJoin('part.etudiant', 'etudiant')
                ->addSelect('etudiant');

        $qb->where('e.statutEtude = :statut')
        ->setParameter('statut', $statut)
        ->andWhere('etudiant.id = :id')
        ->setParameter('id', $idStudent)
        ;

        return $qb
//                ->getQuery()
//                        ->getResult()
                ;
    }

}
