<?php

namespace Junior\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndemnitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndemnitesRepository extends EntityRepository
{
    public function findMontantsAcomptesByIndemnites($indemnites) {
        $acomptes = $indemnites->getAcomptes();
        $montantsAcomptes = array(NULL);
        $cpt = 0;
        
        foreach($acomptes as $acompte) {
            $montantsAcomptes[$cpt] = $acompte->getMontantAcompte();
            $cpt++;
        }
        return $montantsAcomptes;
    }
    
    public function findTotalAcomptesByIndemnites($indemnites) {
        $acomptes = $indemnites->getAcomptes();
        $totalAcomptes = 0;
        
        foreach($acomptes as $acompte) {
            $totalAcomptes += $acompte->getMontantAcompte();
        }
        return $totalAcomptes;
    }
    
  public function findIndembyEtudiantAndEtude($idEtudiant, $idEtude)
  {
        $qb = $this->createQueryBuilder('indem')
//                ->leftJoin('e.participants', 'part')
//                ->addSelect('part')
//                ->leftJoin('part.etudiant', 'etudiant')
//                ->addSelect('etudiant')
                ;

        $qb->where('indem.etudiant = :etudiant')
                ->setParameter('etudiant', $idEtudiant)
                ->andWhere('indem.etude = :etude')
                ->setParameter('etude', $idEtude)
        ;
        
//        $indemEntity =  $qb
//                ->getQuery()
//                        ->getResult();
//        $indem = $indemEntity->getNbJours() * $indemEntity->getIndemniteJournee();
//        
//                return $indem;
                
        return $qb
                ->getQuery()
                        ->getResult()
        ;
  }
    
}
