<?php

namespace Junior\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends EntityRepository {

    public function findEtudesbyEtudiant($idEtudiant) {
        $qb = $this->createQueryBuilder('p')
                ->leftJoin('p.etudiant', 'etudiant')
                ->addSelect('etudiant')
                ->leftJoin('p.etude', 'etude')
                ->addSelect('etude');

        $qb->where('e.id = :id')
                ->setParameter('id', $idEtudiant);

        return $qb;
    }

    public function findParticipantsbyEtudiant($idEtudiant) {
        $qb = $this->createQueryBuilder('p');
//                ->leftJoin('p.etudiant', 'etudiant')
//                ->addSelect('etudiant');

        $qb->where('p.etudiant = :id')
                ->setParameter('id', $idEtudiant);

        return $qb
                        ->getQuery()
                        ->getResult();
    }
    
//    public function getIndemnites($idEtudiant, $idEtude) {
//                $qb = $this->createQueryBuilder('p')
//                ->leftJoin('p.etudiant', 'etudiant')
//                ->addSelect('etudiant')
//                 ->leftJoin('p.indemnites', 'indemn')
//                ->addSelect('indemn');
//
//        $qb->where('p.etudiant = :id')
//                ->setParameter('id', $idEtudiant);
//
//        return $qb
//                        ->getQuery()
//                        ->getResult();
//        
//        
//    }
    

}
