<?php

namespace Junior\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemboursementFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemboursementFraisRepository extends EntityRepository
{
    
    public function findRFbyIdEtudiant($idEtudiant) {
        
        $qb = $this->createQueryBuilder('rf')
                ->leftJoin('rf.frais', 'frais')
                ->addSelect('frais')
                ->leftJoin('frais.etudiant', 'etu')
                ->addSelect('etu')
                ->leftJoin('frais.etude', 'etude')
                ->addSelect('etude');

        $qb->where('etu = :etudiant')
                ->setParameter('etudiant', $idEtudiant)
                ->orderBy('frais.dateAchat', 'DESC');

        return $qb->getQuery()
                        ->getResult();
    }
//    
//    public function nbFraisinRF($idEtudiant) {
//        
//        $qb = $this->createQueryBuilder('rf')
//                ->leftJoin('rf.frais', 'frais')
//                ->addSelect('frais')
//                ->leftJoin('frais.etudiant', 'etu')
//                ->addSelect('etu')
//                ->leftJoin('frais.etude', 'etude')
//                ->addSelect('etude');
//
//        $qb->where('etu = :etudiant')
//                ->setParameter('etudiant', $idEtudiant)
//                ->getQuery();
//        
//        $total = $query->select('COUNT(frais)')
//               ->getQuery()
//               ->getSingleScalarResult();
//
//        return $total;
//    }
    
    
    
}
