junior_etudiant_homepage:
    pattern:  /index
    defaults: { _controller: JuniorEtudiantBundle:Etudiant:index }
    
junior_etudiant_dashboard:
    pattern:  /dashboard
    defaults: { _controller: JuniorEtudiantBundle:Etudiant:dashboard }
    
junior_etudiant_showEtudiant:
    pattern:  /info
    defaults: { _controller: JuniorEtudiantBundle:Etudiant:showEtudiant }
    
junior_etudiant_editEtudiant:
    pattern:  /info/edit
    defaults: { _controller: JuniorEtudiantBundle:Etudiant:editEtudiant }
    
junior_etudiant_updateEtudiant:
    pattern:  /info/update
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:updateEtudiant" }
    requirements: { _method: post|put }

junior_etudiant_listFrais:
    pattern:  /frais
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:listFrais" }
    
junior_etudiant_listRF:
    pattern:  /remboursementfrais
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:listRF" }

junior_etudiant_newFrais:
    pattern:  /frais/new
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:newFrais" }
    
junior_etudiant_showRembFrais:
    pattern:  /remboursementFrais/{idRF}
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:showRembFrais" }
    
junior_etudiant_listEtudes:
    pattern:  /etudes
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:listEtudes" }
    
junior_etudiant_showEtude:
    pattern:  /{idEtude}/etude
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:showEtude" }
    
junior_etudiant_selectEtude:
    pattern:  /acompte/select
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:selectEtude" }    


junior_etudiant_newAcompte:
    pattern:  /{idEtude}/acompte/new
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:newAcompte" }

