junior_etudiant_homepage:
    pattern:  /index
    defaults: { _controller: JuniorEtudiantBundle:Etudiant:index }
    
junior_etudiant_dashboard:
    pattern:  /dashboard
    defaults: { _controller: JuniorEtudiantBundle:Etudiant:dashboard }
    
junior_etudiant_showEtudiant:
    pattern:  /info
    defaults: { _controller: JuniorEtudiantBundle:Etudiant:showEtudiant }
    
junior_etudiant_editEtudiant:
    pattern:  /info/edit
    defaults: { _controller: JuniorEtudiantBundle:Etudiant:editEtudiant }
    
junior_etudiant_updateEtudiant:
    pattern:  /info/update
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:updateEtudiant" }
    requirements: { _method: post|put }

junior_etudiant_listFrais:
    pattern:  /frais
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:listFrais" }

junior_etudiant_newFrais:
    pattern:  /frais/new
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:newFrais" }
    
junior_etudiant_showRembFrais:
    pattern:  /remboursementFrais/{idRF}
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:showRembFrais" }
    
junior_etudiant_listEtudes:
    pattern:  /etudes
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:listEtudes" }
    
junior_etudiant_showEtude:
    pattern:  /{idEtude}/etude
    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:showEtude" }


#routes generees par le crud etudiant, pour info et exemple
#etudiant:
#    pattern:  /
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:index" }
#
#etudiant_show:
#    pattern:  /{id}/show
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:show" }
#
#etudiant_new:
#    pattern:  /new
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:new" }
#
#etudiant_create:
#    pattern:  /create
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:create" }
#    requirements: { _method: post }
#
#etudiant_edit:
#    pattern:  /{id}/edit
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:edit" }
#
#etudiant_update:
#    pattern:  /{id}/update
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:update" }
#    requirements: { _method: post|put }
#
#etudiant_delete:
#    pattern:  /{id}/delete
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:delete" }
#    requirements: { _method: post|delete }
