#junior_gestion_homepage:
#    pattern:  /index
#    defaults: { _controller: JuniorEtudiantBundle:Etudiant:index }
    
junior_gestion_dashboard:
    pattern:  /dashboard
    defaults: { _controller: JuniorEtudiantBundle:Gestion:dashboard }
    
#ETUDIANTS

junior_gestion_listEtudiants:
    pattern: /etudiants
    defaults: { _controller: JuniorEtudiantBundle:Gestion:listEtudiants }

junior_gestion_showEtudiant:
    pattern: /{idEtudiant}/etudiant
    defaults: { _controller: JuniorEtudiantBundle:Gestion:showEtudiant }

junior_gestion_newEtudiant:
    pattern: /etudiant/new
    defaults: { _controller: JuniorEtudiantBundle:Gestion:newEtudiant }
    
junior_gestion_editEtudiant:
    pattern: /etudiant/{idEtudiant}/edit
    defaults: { _controller: JuniorEtudiantBundle:Gestion:editEtudiant }
    
junior_gestion_deleteEtudiant:
    pattern: /etudiant/delete
    defaults: { _controller: JuniorEtudiantBundle:Gestion:deleteEtudiant }
    
#ACOMPTES
    
junior_gestion_listAcomptes:
    pattern: /acomptes
    defaults: { _controller: JuniorEtudiantBundle:Gestion:listAcomptes }
    
junior_gestion_validAcompte:
    pattern: /acompte/validation
    defaults: { _controller: JuniorEtudiantBundle:Gestion:validAcompte }
    
junior_gestion_showAcompte:
    pattern: /acompte
    defaults: { _controller: JuniorEtudiantBundle:Gestion:showAcompte }
    
#FRAIS
    
junior_gestion_listFrais:
    pattern: /frais
    defaults: { _controller: JuniorEtudiantBundle:Gestion:listFrais }
    
junior_gestion_sortFrais:
    pattern: /frais/sort
    defaults: { _controller: JuniorEtudiantBundle:Gestion:sortFrais }
    
junior_gestion_validFrais:
    pattern: /frais/validation
    defaults: { _controller: JuniorEtudiantBundle:Gestion:validFrais }
    
#REMBOURSEMENT DE FRAIS
    
junior_gestion_newRF:
    pattern: /remboursementfrais/new
    defaults: { _controller: JuniorEtudiantBundle:Gestion:newRF }
    
junior_gestion_showRF:
    pattern: /remboursementfrais
    defaults: { _controller: JuniorEtudiantBundle:Gestion:showRF }
    
#ETUDES
    
junior_gestion_listEtudes:
    pattern: /etudes
    defaults: { _controller: JuniorEtudiantBundle:Gestion:listEtudes }
    
junior_gestion_showEtude:
    pattern: /{idEtude}/etude
    defaults: { _controller: JuniorEtudiantBundle:Gestion:showEtude }
    
junior_gestion_newEtude:
    pattern: /{idConvention}/etude/new
    defaults: { _controller: JuniorEtudiantBundle:Gestion:newEtude }
    
junior_gestion_newGroupe:
    pattern: /{idEtude}/etude/groupe/new
    defaults: { _controller: JuniorEtudiantBundle:Gestion:newGroupe }
    
junior_gestion_editEtude:
    pattern: /etude/edit
    defaults: { _controller: JuniorEtudiantBundle:Gestion:editEtude }
    
junior_gestion_closeEtude:
    pattern: /{idEtude}/etude/close
    defaults: { _controller: JuniorEtudiantBundle:Gestion:closeEtude }
    
#ENTREPRISES
    
junior_gestion_choixEntreprise:
    pattern: /entreprise/choix
    defaults: { _controller: JuniorEtudiantBundle:Gestion:choixEntreprise }
    
junior_gestion_newEntreprise:
    pattern: /entreprise/new
    defaults: { _controller: JuniorEtudiantBundle:Gestion:newEntreprise }
    
#CONVENTIONS

junior_gestion_newConvention:
    pattern: /{idEntreprise}/convention/new
    defaults: { _controller: JuniorEtudiantBundle:Gestion:newConvention }
    
#junior_etudiant_showEtudiant:
#    pattern:  /{id}/info
#    defaults: { _controller: JuniorEtudiantBundle:Etudiant:showEtudiant }
#    
#junior_etudiant_editEtudiant:
#    pattern:  /{id}/info/edit
#    defaults: { _controller: JuniorEtudiantBundle:Etudiant:editEtudiant }
#    
#junior_etudiant_updateEtudiant:
#    pattern:  /{id}/info/update
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:updateEtudiant" }
#    requirements: { _method: post|put }
#
#junior_etudiant_listFrais:
#    pattern:  /{id}/frais
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:listFrais" }
#
#junior_etudiant_newFrais:
#    pattern:  /{id}/frais/new
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:newFrais" }
#    
#junior_etudiant_listEtudes:
#    pattern:  /{id}/etudes
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:listEtudes" }
#    
#junior_etudiant_showEtude:
#    pattern:  /{idEtude}/{idEtudiant}/etude
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:showEtude" }
#
#
##routes generees par le crud etudiant, pour info et exemple
#etudiant:
#    pattern:  /
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:index" }
#
#etudiant_show:
#    pattern:  /{id}/show
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:show" }
#
#etudiant_new:
#    pattern:  /new
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:new" }
#
#etudiant_create:
#    pattern:  /create
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:create" }
#    requirements: { _method: post }
#
#etudiant_edit:
#    pattern:  /{id}/edit
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:edit" }
#
#etudiant_update:
#    pattern:  /{id}/update
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:update" }
#    requirements: { _method: post|put }
#
#etudiant_delete:
#    pattern:  /{id}/delete
#    defaults: { _controller: "JuniorEtudiantBundle:Etudiant:delete" }
#    requirements: { _method: post|delete }
