jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
        Junior\UserBundle\Entity\Etudiant: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ETUDIANT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        main:
           entity: { class: Junior\EtudiantBundle\Entity\Etudiant, property: username }
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
          pattern:    ^/
          anonymous: true
          provider:  main
          form_login:
            login_path: fos_user_security_login
            check_path: fos_user_security_check
          logout:
            path: fos_user_security_logout
            target: /login
#          remember_me:
#            key: %secret%





          form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
          logout:       true
          

#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/etudiant/, role: ROLE_ADMIN }
        
