junior_etudiant_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JuniorEtudiantBundle:Default:index }
    
junior_etudiant_dashboard:
    pattern:  /dashboard
    defaults: { _controller: JuniorEtudiantBundle:Default:dashboard }
