parameters:
  junior_etudiant.services.authentication.login_success_handler.class: Junior\EtudiantBundle\Services\Authentication\LoginSuccessHandler


services:
#  service permettant une bonne redirection de l'url après login, selon le role de la personne qui se connecte
  junior_etudiant.services.authentication.login_success_handler: 
    class: %junior_etudiant.services.authentication.login_success_handler.class%
    arguments: ["@router", "@security.context"]
    tags:
      - { name: 'monolog.logger', channel: 'security' }
 